### ISSUE TITLE
outdated version string in demo

### ISSUE THREAD

**Issue by DanielRuf** [terser/html-minifier-terser#103]
https://github.com/terser/html-minifier-terser/blob/master/demo/index.html#L19

Should be probably v6.1.0.

**Comment by DanielRuf** [comment]
Currently not sitting on a PC.

Can you check why https://terser.org/html-minifier-terser/ does not work @sibiraj-s? That would be great.

**Comment by sibiraj-s** [comment]
Checking.

**Comment by sibiraj-s** [comment]
@DanielRuf. Fixed now. now a days bundlers don't handle `process` variables defined in the code. hence the issue. Should work now.

**Comment by DanielRuf** [comment]
> Should work now.

Looks and works great =)
