### ISSUE TITLE
demo site fails with Minify CSS enabled

### ISSUE THREAD

**Issue by AndrJ** [terser/html-minifier-terser#110]
Hi
Thanks for developing this! 

When I enable Minify CSS, I get the following error on the domo site:
`ReferenceError: process is not defined`

https://terser.org/html-minifier-terser/
```
<!doctype html>
<html>
<head>
  <style>
    p {
      color: red;
    }
  </style>
</head>
<body>
  <p>This is my paragraph.</p>
</body>
</html>
```

**Comment by DanielRuf** [comment]
![grafik](https://user-images.githubusercontent.com/827205/153034287-55d2e6eb-b31b-4e2d-909c-697d99f5ed63.png)

@sibiraj-s I guess this is related to some check that should not happen on browsers (process.env?). Maybe we have to check first if `process` is defined (`typeof process !== 'undefined'` or `process &&`).

**Comment by sibiraj-s** [comment]
Yeah. Will fix that. We'll need to polyfill for node while building for web.

**Comment by DanielRuf** [comment]
Perfect, works again now =)

![grafik](https://user-images.githubusercontent.com/827205/153220553-b378b8bc-944e-4396-b32c-5d5ed541bedb.png)

**Comment by AndrJ** [comment]
Thank you!
it is perfect!:blush:
