### ISSUE TITLE
[BUG] minifyCSS parsing error if css class contains double dash (--) 

### ISSUE THREAD

**Issue by mikethm** [terser/html-minifier-terser#125]
Minifying the following gives a blank style. 
It appears that if a comment is the first line, the next line is missed if the name has a double dash (e.g. in BEM naming convention)
```
<style>

.double--dash {
    /* the line after this is ignored */
    content: "hi";   
}

</style>

```

**Comment by DanielRuf** [comment]
Hi @mikethm,

thanks for reporting this.

html-minifier uses a thirdparty dependency for CSS minifying. So if there is a bug please check this with `clean-css`: https://github.com/terser/html-minifier-terser/blob/v7.0.0-alpha.2/package.json#L78

https://github.com/clean-css/clean-css

Closing as I can reproduce this at https://clean-css.github.io/

Please report your finding at https://github.com/clean-css/clean-css/issues.

**Comment by sibiraj-s** [comment]
The fix is merged but not yet released https://github.com/clean-css/clean-css/commits/master

**Comment by DanielRuf** [comment]
Not sure if this also covers the normal rules without `@...`: https://github.com/clean-css/clean-css/commit/40ca65807639e0470dab22585847a7582687167f#diff-8293806213899c77041113555d21f05f403e84479eb1b480180e2c486cf9b2bdL361
