### ISSUE TITLE
[Bug]: JUST FULLY ERR!

### ISSUE THREAD

**Issue by gowy222** [terser/html-minifier-terser#145]
### What happened?

try this:

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en-US"><head>    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />    <meta name="viewport" content="width=device-width, initial-scale=1.0"/></head><body style="margin: 0; padding: 0; border: none; background:#faf9f8" width="100%">    <table role="presentation" align="center" cellpadding="0" cellspacing="0" width="613" style="border:1px solid #CCCCCC;color: #4e5052;border-collapse: collapse; font-family: Arial, Helvetica, sans-serif; bgcolor="#FFF">        <tr>            <td colspan="2">                <img style="width:614px;" src="https://signup-api.oraclecloud.com/20200828/media/emailHeader">            </td>        </tr>        <tr style="min-height:200px;background:#FFFFFF;color:#7b7b7b;">            <td colspan="2" width="613" style="overflow-wrap: break-word;word-wrap: break-word; padding: 20px 15px;border-bottom:1px solid #7b7b7b;">                <p>Hello, </p><br>                <p>Thanks for your interest in creating an Oracle Cloud account. To create your account, please verify your email address by clicking below.<br><br><a href="https://signup.cloud.oracle.com?verify_email=eyJhbGciOiJIUzI1NiXXXXXXXXXXXXXXXXXXXXXX=:ow:o:p:nav:080000IHeroCalloutcn:ow:o:p:feb:0916FreePageMidButton"><img src="https://signup.cloud.oracle.com/images/verify-email-button.png"></a></p><br><p>Thanks,</p><br><p>The Oracle Cloud Team</p><br><br>            </td>        </tr>        <tr width="613" style="background:#FFFFFF;color:#7b7b7b;font-size:10px;">            <td style="width:30%">                <img src="https://signup-api.oraclecloud.com/20200828/media/email-footer-logo">            </td>            <td style="width:70%;text-align:right;padding:5px">                <div style="margin-right:5px; margin-bottom:2px;">Please do not reply directly to this email.</div>                <div style="margin-right:5px; margin-bottom:2px;">Copyright &copy; 2020 Oracle.  All rights reserved.</span>                <div style="margin-right:5px;"><a style="color:#838586;text-decoration:none" href="https://www.oracle.com/corporate/contact/">Contact Us</a> | <a style="color:#838586;text-decoration:none" href="https://www.oracle.com/legal/terms.html">Legal Notices and Terms of Use</a> | <a style="color:#838586;text-decoration:none" href="https://www.oracle.com/legal/privacy/">Privacy Statement</a></div>                            </td>        </tr>    </table></body></html>`

### Version

V7

### What browsers are you seeing the problem on?

Chrome

### Willing to submit a PR?

None

**Comment by gowy222** [comment]
Error: Parse Error: <table ...

**Comment by DanielRuf** [comment]
You are missing the closing `"` there (after `sans-serif;`):

> style="border:1px solid #CCCCCC;color: #4e5052;border-collapse: collapse; font-family: Arial, Helvetica, sans-serif; bgcolor="#FFF">

Should be:

> style="border:1px solid #CCCCCC;color: #4e5052;border-collapse: collapse; font-family: Arial, Helvetica, sans-serif;" bgcolor="#FFF">

**Comment by gowy222** [comment]
thx the replay, but this was an email from Oracle Cloud... it works and showed ok in chrome... 
so, is there anyway to try minifier this kinda "broken" html string..

**Comment by DanielRuf** [comment]
> so, is there anyway to try minifier this kinda "broken" html string..

No, since only valid html can be parsed.
