### ISSUE TITLE
Src included in build?

### ISSUE THREAD

**Issue by multivoltage** [terser/html-minifier-terser#157]
this package is 4.6 mb, probably because **files** in **package.json** has also "src" folder.
Can we remove that from the build?

**Comment by sibiraj-s** [comment]
See https://github.com/terser/html-minifier-terser/blob/master/package.json#L48. ESM directly points to src. Suggestions welcome, but I don't see anything unwanted being published.

**Comment by multivoltage** [comment]
Sorry. I did not notice that esm point to source. Thank for answer ;)
