### ISSUE TITLE
Feature: Collapse whitespace into a single space

### ISSUE THREAD

**Issue by nex3** [terser/html-minifier-terser#184]
[The documentation](http://perfectionkills.com/experimenting-with-html-minifier/#collapse_whitespace) indicates that this is a desirable feature:

> Second option is to never fully remove white space characters, and instead always collapse them to one white space character. HTML 4.01 is actually [specified to do just that](http://www.w3.org/TR/html401/struct/text.html#whitespace), so there’s no harm in doing it upfront. Because of this, the following 2 snippets should render identically:
>
>
> ```html
> <span>foo</span>
> 
>    <span>bar</span>
> ```
>
> and:
>
> ```html
>  <span>foo</span> <span>bar</span>
> ```
>
> ...with one space in between “foo” and “bar”. Note how in first case, there’s an entire sequence of white space characters (including line breaks).
>
> This second option—collapsing to one white space—has not yet been added to minifier.

But I don't see a tracking issue for it yet.

**Comment by codemzy** [comment]
I think you can do this with:

```js
const { minify } = require('html-minifier-terser');

const result = await minify(`<span>foo</span>

   <span>bar</span>`, {
  collapseWhitespace: true, // removes whitespace
  conservativeCollapse: true, // collapse to 1 space (never remove it entirely)
});
```

**Comment by nex3** [comment]
Ah, you're right!
