### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mrgaton** [terser/html-minifier-terser#185]
Instead of always having to use teser or clean-css be able to modify the data personaly

**Comment by DanielRuf** [comment]
Can you describe in detail, what the exact issue is?

This is a tool to automate optimizations, not some interactive CLI or IDE extension.

**Comment by Mrgaton** [comment]
Instead of using tester to minify js be able to minify myself the data via a function

**Comment by DanielRuf** [comment]
Take a look at the `minifyJS` configuration setting, which allows you to define a custom function - or exactly what you are looking for.

https://github.com/terser/html-minifier-terser?tab=readme-ov-file#options-quick-reference
