### ISSUE TITLE
check open PRs

### ISSUE THREAD

**Issue by DanielRuf** [terser/html-minifier-terser#19]
We should check the PRs at https://github.com/kangax/html-minifier/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc and see if we have to merge some to fix a few issues.

**Comment by rodrigograca31** [comment]
really quick look and only this PR seems good to be applied:
https://github.com/kangax/html-minifier/pull/1044

**Comment by DanielRuf** [comment]
Hi @rodrigograca31,

This was applied in https://github.com/DanielRuf/html-minifier-terser/commit/3a72ed210af15ffce811beb9ae127089c37abe26.

**Comment by DanielRuf** [comment]
Related issue: https://github.com/DanielRuf/html-minifier-terser/issues/2

**Comment by rodrigograca31** [comment]
Oh, nice! glad to see that!
I only had a quick look :)

**Comment by DanielRuf** [comment]
Closing as this is a general task for the project.
