### ISSUE TITLE
Test CLI

### ISSUE THREAD

**Issue by DanielRuf** [terser/html-minifier-terser#33]
https://github.com/DanielRuf/html-minifier-terser/commit/93ac5b39f67c6dc7da370bc2cf759568a6b3c62e and https://github.com/DanielRuf/html-minifier-terser/commit/03bc8d1e23b73ecd789e00d4035a32eae4fe3e41 broke the `require` statement as they are different now. This was fixed in https://github.com/DanielRuf/html-minifier-terser/commit/9f2d2347a0df20031223ceabf75669fb53f8b895

But this was just found while manually testing with the CLI. So we should also test the CLI.

**Comment by sibiraj-s** [comment]
Closed via #94
