### ISSUE TITLE
`&quot;//` was incorrectly converted to `&quot;/`

### ISSUE THREAD

**Issue by little-tomorrow** [terser/html-minifier-terser#52]
### Environment

* html-minifier-terser version: 5.1.1
* node.js version - `node -v`: v10.23.0
* operating system: macos 10.15.7

### Input

```js
const { minify } = require('html-minifier-terser');
const output = minify(`
<div style="background-image:url(&quot;//www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png&quot;)"></div>
`, {
  minifyCSS: true,
});
console.log(output)
```

### Actual output

```js
<div style="background-image:url(&quot;/www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png&quot;)"></div>
```

### Expected output

```js
<div style="background-image:url(&quot;//www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png&quot;)"></div>
```

After opening minifyCSS, `&quot;//` will be converted into `&quot;/`. Eventually cause the picture to fail

**Comment by little-tomorrow** [comment]
I reproduce this bug in both html-minifier and html-minifier-terser. So I opened the issue in both projects.

**Comment by DanielRuf** [comment]
For the css part we use a thirdparty library. I wll check that in detail, maybe there is a bug, but probably not on our side.

Besides this, protocoll-less URLs are rarely a good idea.

**Comment by DanielRuf** [comment]
I can not reproduce it on https://terser.org/html-minifier-terser/ with the default settings.

**Comment by DanielRuf** [comment]
Ah now I can reproduce it. It happens when you disable `Decode Entity Characters`.

Why do you use `&quot;` instead of `"`?

**Comment by DanielRuf** [comment]
The following works and is valid HTML:

> <div style="background-image:url('//www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png')"></div>

The `&quot;` makes no sense and is no valid HTML and not the correct way to escape the character.

Closing as "not a bug".

**Comment by little-tomorrow** [comment]
> Ah now I can reproduce it. It happens when you disable `Decode Entity Characters`.
> 
> Why do you use `&quot;` instead of `'`?

the html is generated using a puppeteer.

**Comment by DanielRuf** [comment]
Then puppeteer or the part who generates it has an issue. Please check the `Decode Entity Characters` option.

**Comment by little-tomorrow** [comment]
check the `Decode Entity Characters` option, it work. thank.
