### ISSUE TITLE
Why not provide a specific property  to clear the html source tag？

### ISSUE THREAD

**Issue by ZLhake** [terser/html-minifier-terser#62]
please provide a property  to clear the html tag，such as 'removeTags' ,we can use this property to remove some tag content that we do not need  In the compiled html file

**Comment by DanielRuf** [comment]
Hi,

what exactly would be the use case?
html-minifier does not remove unwanted tags and is mainly for minifying code (that's why it is called minifier).

Removing whole elements with contents is out of scope of this library.

**Comment by ZLhake** [comment]
> Hi,
> 
> what exactly would be the use case?
> html-minifier does not remove unwanted tags and is mainly for minifying code (that's why it is called minifier).
> 
> Removing whole elements with contents is out of scope of this library.
First of all, thank you for your reply. In our project, it is a multi-page project. Our scripts are introduced in the head of HTML, so we don’t need to package and compile during development, and can run directly in the browser, but Our project needs to be packaged before it goes online. When packaging, you need to comment out all the script and link tags in the HTML, and then package and compile through webpack. Because there are too many pages, the operation is too troublesome, so we hope to provide such a method to facilitate our operation

**Comment by DanielRuf** [comment]
This sounds more like a webpack configuration issue and there are webpack plugins to replace / remove elements during compilation.

https://www.google.com/search?channel=fs&q=webpack+replace+plugin

**Comment by DanielRuf** [comment]
Closing as this is not planned as feature in html-minifier(-terser).
