### ISSUE TITLE
When we will have new version?

### ISSUE THREAD

**Issue by amerllica** [terser/html-minifier-terser#66]
As everyone knows there are several merged PRs after 14th May 2020, so when do we have the new version?

**Comment by DanielRuf** [comment]
When I find some free time do prepare a new release, write the changelog and publish it to npmjs.

**Comment by DanielRuf** [comment]
Probably this friday, ut this is not 100% sure.

**Comment by DanielRuf** [comment]
Probably this friday, but this is not 100% sure.

**Comment by amerllica** [comment]
Dankeschön @DanielRuf

**Comment by amerllica** [comment]
Dear @DanielRuf, please release the next version, I know you are busy, but we are in bad pressure, I'm begging now 😞.

**Comment by DanielRuf** [comment]
html-minifier-terser v6.0.0 has been released now: https://www.npmjs.com/package/html-minifier-terser

If someone wants to help with the changelog, that would be great.

https://github.com/terser/html-minifier-terser/releases/tag/v6.0.0

**Comment by amerllica** [comment]
I love you @DanielRuf ❤️
