### ISSUE TITLE
[FEATURE]: Add new CLI argument to add extra content to the output file

### ISSUE THREAD

**Issue by Chris2011** [terser/html-minifier-terser#68]
It would be good, to have a new CLI argument to add extra stuff to the output file automatically. My NetBeans plugin has a JEditorPane and when I add stuff there, every file that is will be minifed needs to have this content automatically added to the outpuf file. Yes, I can add this in another way like after the output file was created, I can add this, but I think it would be better to have such a cli argument. What do you think?

**Comment by DanielRuf** [comment]
Hi @Chris2011,

thanks for your suggestion.
But so far I see no good reason to add this feature to html-minifier-terser which only minifies the output.

Normally you have a build setup with webpack and plugins to replace strings.
Generally you can already use this:
https://github.com/terser/html-minifier-terser#ignoring-chunks-of-markup

In my opinion this feature request is out of scope of this library.

**Comment by Chris2011** [comment]
Thx, will try what you mentioned. Thx.
