### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [terser/html-minifier-terser#70]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by DanielRuf** [comment]
Hi @zidingz,

please send me the details to kontakt@daniel-ruf.de. Also there is my email address in every commit message.

**Comment by DanielRuf** [comment]
I think there went something terribly wrong with huntr:

I've got 6 emails, 5 of them with the same subject line:

> [ Cross-Site Request Forgery (CSRF) ] New Security Issue in cachet

> [ Unimplemented or Unsupported Feature in UI ] New Security Issue in cachet

> [ Insufficient Documentation of Error Handling Techniques ] New Security Issue in cachet

> [ Insufficient Documentation of Error Handling Techniques ] New Security Issue in cachet

> [ Insufficient Documentation of Error Handling Techniques ] New Security Issue in cachet

> [ Insufficient Documentation of Error Handling Techniques ] New Security Issue in cachet

Totally different project and it seems you reported these things to a fork of the original project, which makes not that much sense.

<img width="654" alt="Bildschirmfoto 2021-09-01 um 19 27 38" src="https://user-images.githubusercontent.com/827205/131716683-039c9700-6354-41cb-8431-7017c5f30d85.png">

<img width="783" alt="Bildschirmfoto 2021-09-01 um 19 25 36" src="https://user-images.githubusercontent.com/827205/131716315-a2345c42-ef00-48fa-9760-16da6f185218.png">


Also leaking details regarding other unrelated projects is not great either:

<img width="398" alt="Bildschirmfoto 2021-09-01 um 19 26 43" src="https://user-images.githubusercontent.com/827205/131716445-003b911a-6ad6-43a1-ada3-2bea711a7d63.png">

Sending details to the wrong persons is critical. Please check this with your team before sending any emails and better remove this "other advisories" part on the right side which leaks details regarding different projects. It seems your team and project lack some good security practices in general @JamieSlome

**Comment by JamieSlome** [comment]
@DanielRuf - thanks for your comments and for sharing this with us.

With regards to the e-mails, I apologise that these were sent over to you. We have identified the cause and will be reviewing this tomorrow to ensure it doesn't happen again.

The links provided for other projects on reports are only visible if the vulnerability has been patched, and so no details are being leaked cross-projects.

Nonetheless, I will review your comments with the team and thank you for your patience! 🍰
