### ISSUE TITLE
Invalid Arg Type Error on minify

### ISSUE THREAD

**Issue by Chris2011** [terser/html-minifier-terser#71]
I installed version 6.0.0 from html-minifier-terser. In the CLI I tried -> html-minifier-terser index.html --output index.min.html and I got this error:

```
C:\temp>html-minifier-terser index.html --output index.min.html
internal/streams/writable.js:285
      throw new ERR_INVALID_ARG_TYPE(
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Promise
←[90m    at WriteStream.Writable.write (internal/streams/writable.js:285:13)←[39m
    at writeMinify (C:\Users\Chris\AppData\Roaming\npm\node_modules\←[4mhtml-minifier-terser←[24m\cli.js:288:24)
    at Object.<anonymous> (C:\Users\Chris\AppData\Roaming\npm\node_modules\←[4mhtml-minifier-terser←[24m\cli.js:305:3)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'ERR_INVALID_ARG_TYPE'←[39m
}
```

Did I miss smth or did the syntax for the CLI changed?

Windows 10 (64bit)
Node: 14.16.0
NPM: 7.5.2

**Comment by DanielRuf** [comment]
v6.0.0 uses aync / await. See also the readme regarding the usage.

Not sure if we have to change something in the CLI. PRs are very welcome.

**Comment by DanielRuf** [comment]
@sibiraj-s can you check this?

**Comment by Chris2011** [comment]
I use the same arguments/syntax as with version 5.1.1. Will check the readme again.

**Comment by DanielRuf** [comment]
> Not sure if we have to change something in the CLI.

@Chris2011 it's probably due to the changes in https://github.com/terser/html-minifier-terser/pull/63
No error on your side.

**Comment by Chris2011** [comment]
Ok, thx for the info.

**Comment by sibiraj-s** [comment]
> @sibiraj-s can you check this?

Sure

**Comment by Chris2011** [comment]
Thx for the fast fix, just want to know when the new version will be ready.

**Comment by DanielRuf** [comment]
@Chris2011 v6.0.1 is now published on npmjs.

**Comment by Chris2011** [comment]
Great thx :)

**Comment by laurentpayot** [comment]
I had to open https://github.com/terser/html-minifier-terser/issues/74 for a similar issue on v6.0.1

**Comment by Chris2011** [comment]
After using 6.0.2 everything works as before. Thx :)
