### ISSUE TITLE
New release has a weird bug!

### ISSUE THREAD

**Issue by amerllica** [terser/html-minifier-terser#77]
Hello again, Based on [this issue](https://github.com/terser/html-minifier-terser/issues/64) I send [this PR](https://github.com/terser/html-minifier-terser/issues/64) for updating Clean-CSS, and when this package was released on version 6+, I updated this package on my project, but after bundle I just see `{}` for rendered HTML on browser.

We downgrade to `5.1.1` and everything is ok now.

I considered it my duty to report it. if need any more data please tell me. I will share to prevent this weird bug.

**Comment by DanielRuf** [comment]
Please provide the details about the exact version that you use and how you use html-minifier-terser so this can be reproduced.

**Comment by DanielRuf** [comment]
Please also see the readme / docs regarding the new API based on async/await.

**Comment by sibiraj-s** [comment]
@amerllica. As @DanielRuf mentioned the minify api is now async. Closing this issue for now. Reopen with more information if the issue still persists.
