### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by DanielRuf** [terser/html-minifier-terser#79]
html-minifier-terser is looking for a new longterm maintainer.

Maybe this is something for you or the webpack team @alexander-akait @sibiraj-s.

**Comment by alexander-akait** [comment]
Thanks, but unfortunately I don't have time now on new features, but you can invite me and if something needs to be updated or there is a critical problem, I will try to fix it soon

**Comment by sibiraj-s** [comment]
Thanks @DanielRuf . Happy to help. I might not be able to proactively take up new features, but can keep this lib upto date, fix bugs and other maintenance related stuffs.

**Comment by DanielRuf** [comment]
Thank you very much @alexander-akait and @sibiraj-s, I have added you both with maintainer rights to this repository.

Can you provide me your npm usernames / handles? Then I can add you both there too so you can publish new releases.

Currently there is one thing left that I have to do and make a new release but so far I had not the time to do this. I'll try to resolve it this week but I can not promise it.

**Comment by sibiraj-s** [comment]
My npm handle [sibiraj-s](https://www.npmjs.com/~sibiraj-s)

**Comment by alexander-akait** [comment]
npm - [evilebottnawi](https://www.npmjs.com/~evilebottnawi)

**Comment by DanielRuf** [comment]
Great, I've added you both as maintainers for the package on npmjs.
I'm very grateful for the support, thank you very much!

> Currently there is one thing left that I have to do and make a new release but so far I had not the time to do this. I'll try to resolve it this week but I can not promise it.

This one is still open but I did not forget it.

**Comment by DanielRuf** [comment]
I'm closing this issue since the new maintainers shoudl have the needed rights. If something does not work or missing regarding the access, please let me know.

And I will try to to the last open thing / task during my vacation next week.

Thank you very much =)

**Comment by sibiraj-s** [comment]
Sure, thanks @DanielRuf .
